

#ifndef STM32_PROJECT_TYPES_H
#define STM32_PROJECT_TYPES_H

#endif //STM32_PROJECT_TYPES_H

#include "std_types.h"

typedef volatile uint32 __IO;
typedef volatile const uint32 __I;
typedef volatile uint32 __O;


/*typedef enum {
    NO_ERROR = 0,              *< NO_ERROR
    ERROR_CANNOT_BE_PROCESSED, *< ERROR_CANNOT_BE_PROCESSED
    ERROR_INCORRECT_DEVICE,    *< ERROR_INCORRECT_DEVICE
    ERROR_BAD_PARAMETERS,      *< ERROR_BAD_PARAMETERS
    ERROR_NOT_ALIGNED,         *< ERROR_NOT_ALIGNED
    ERROR_OUT_OF_BOUND,        *< ERROR_OUT_OF_BOUND
    ERROR_OUT_OF_RANGE,        *< ERROR_OUT_OF_RANGE
    ERROR_INTERNAL_FAILURE,    *< ERROR_INTERNAL_FAILURE
    ERROR_NACK,                *< ERROR_NACK
    ERROR_NOT_ENOUGH_RECEIVED, *< ERROR_NOT_ENOUGH_RECEIVED
    ERROR_NO_BEST_CHANNEL,     *< ERROR_NO_BEST_CHANNEL
    ERROR_LOCKED,              *< ERROR_LOCKED
    ERROR_FAILED,              *< ERROR_FAILED
    ERROR_NOT_READY,           *< ERROR_NOT_READY
    ERROR_NOT_POWERED,         *< ERROR_NOT_POWERED
    ERROR_ALREADY_RUNNING,     *< ERROR_ALREADY_RUNNING
    ERROR_BAD_CLOCK,           *< ERROR_BAD_CLOCK
    ERROR_ACCESS_DENIED        *< ERROR_ACCESS_DENIED
} PRJ_error_type;*/

