/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STM32F446RE_Base.h"
//#include "gpio.h"
//#include "rcc.h"
#include "uart.h"
#include "timer.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  //#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif




uint32 saveCaptureTime = 0;

int main(void){


    StartTimer_OutputCompare(TIM_2,TIMER_TICK_US_1HZ(ONE_SECOND));

    StartTimer_InputCapture(TIM_3,TIMER_TICK_US_1HZ(ONE_SECOND));

    while(1){

    	while (!(TIM_3->SR & SR_CC1IF)){

    		//read captured value
    		saveCaptureTime = TIM_3->CCR1;

    	}

    	saveCaptureTime = 0;
    }

    return 0;
}
//uint8 key;

/*int main(void){

	gpio_config_t x;
	x.direction = OUTPUT;

	vDoConfigDirection(GPIO_PORT_A,PIN_5,x);

    vDoUSARTx_cfg();

    StartTimer(TIM_2,TIMER_TICK_US_1HZ(ONE_SECOND));

    //StartTimer_OutputCompare(TIM_2,TIMER_TICK_US_1HZ(ONE_SECOND));;

    while(1){
    	while(!(TIM_2->SR & SR_UIF)){

    	}

    	TIM_2->SR &=~SR_UIF;
        vDoWriteUSART_data(0x21);


       // key = vDoReadUSART_data();

    }

    return 0;
}*/
