/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STM32F446RE_Base.h"
#include "gpio.h"
#include "rcc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  //#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void main(void){
	uint32 i = 0;
	vDo_AHB1ENR_EnableClockAccessToPort(GPIO_PORT_A);
    gpio_config_t cfg_reg;
    cfg_reg.direction = OUTPUT;
	vDoConfigDirection(GPIO_PORT_A, PIN_1, cfg_reg);

	while(1){

		vDoSetPin(GPIO_PORT_A,PIN_1,SET);

		for(i=0; i<=100000;i++){

			if (i==10000000)
			{
				i=0;
			}
		}
		vDoSetPin(GPIO_PORT_A,PIN_1,RESET);
	}

}

